# Generated by Django 3.2.16 on 2023-06-22 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True, verbose_name='категория')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='ProductsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=150, unique=True, verbose_name='продукт')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='количество')),
                ('image', models.ImageField(upload_to='products_image')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsmodel', to='olga.categorymodel')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
